#!/usr/bin/env python3
"""
Cookies.txt Generator for YouTube Downloader

This script helps generate a cookies.txt file from your browser
for use in production environments where browser cookie extraction isn't available.

Usage:
    python generate_cookies.py

Requirements:
    pip install browser-cookie3
"""

try:
    import browser_cookie3
    import os
except ImportError:
    print("Error: browser-cookie3 not installed")
    print("Install with: pip install browser-cookie3")
    exit(1)

def extract_youtube_cookies():
    """Extract YouTube cookies and save to cookies.txt file"""
    
    browsers = {
        'chrome': browser_cookie3.chrome,
        'firefox': browser_cookie3.firefox,
        'edge': browser_cookie3.edge,
        'safari': browser_cookie3.safari,
        'opera': browser_cookie3.opera
    }
    
    cookies_txt = []
    success = False
    
    for browser_name, browser_func in browsers.items():
        try:
            print(f"Trying to extract cookies from {browser_name}...")
            
            # Get cookies for YouTube domain
            cj = browser_func(domain_name='youtube.com')
            
            # Convert to Netscape format
            for cookie in cj:
                if 'youtube.com' in cookie.domain:
                    # Netscape format: domain, domain_specified, path, secure, expires, name, value
                    line = f"{cookie.domain}\t{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t{cookie.path}\t{'TRUE' if cookie.secure else 'FALSE'}\t{int(cookie.expires) if cookie.expires else 0}\t{cookie.name}\t{cookie.value}"
                    cookies_txt.append(line)
            
            if cookies_txt:
                print(f"✅ Successfully extracted {len(cookies_txt)} cookies from {browser_name}")
                success = True
                break
                
        except Exception as e:
            print(f"❌ Failed to extract from {browser_name}: {str(e)}")
            continue
    
    if success and cookies_txt:
        # Write to cookies.txt file
        output_file = 'cookies.txt'
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by YouTube Downloader Cookie Generator\n")
            f.write("# This file contains cookies for youtube.com\n\n")
            
            for line in cookies_txt:
                f.write(line + '\n')
        
        print(f"✅ Cookies saved to {output_file}")
        print(f"📁 File size: {os.path.getsize(output_file)} bytes")
        print("\n🚀 Next steps:")
        print("1. Upload cookies.txt to your server")
        print("2. Set environment variable: YT_DLP_COOKIES_FILE=/path/to/cookies.txt")
        print("3. Remove YT_DLP_COOKIES_FROM_BROWSER if set")
        print("\n⚠️  Security note: Keep cookies.txt secure - it contains authentication data")
        
        return True
    else:
        print("❌ Failed to extract cookies from any browser")
        print("\n💡 Troubleshooting:")
        print("1. Make sure you're logged into YouTube in your browser")
        print("2. Try visiting youtube.com before running this script")
        print("3. Close your browser and try again")
        print("4. Try running as administrator/sudo")
        
        return False

if __name__ == "__main__":
    print("🍪 YouTube Cookie Extractor")
    print("=" * 40)
    
    if extract_youtube_cookies():
        print("\n✅ Cookie extraction completed successfully!")
    else:
        print("\n❌ Cookie extraction failed!")
        print("Consider manually exporting cookies using a browser extension.")
